# Generated by Django 6.0.1 on 2026-01-12 15:39

from django.db import migrations


def populate_categories(apps, schema_editor):
    category = apps.get_model('online_store', 'Category')
    category.objects.bulk_create([
        category(
            name='Процессоры',
            description='Центральные процессоры (CPU) — основные вычислительные элементы компьютера, выполняющие арифметические и логические операции.',
        ),
        category(
            name='Материнская плата',
            description='Основная печатная плата компьютера, обеспечивающая соединение и взаимодействие всех компонентов системы.',
        ),
        category(
            name='Видеокарты',
            description='Графические процессоры (GPU), отвечающие за обработку и вывод графических данных.',
        ),
        category(
            name='Оперативная память',
            description='Временное хранилище данных, используемое процессором для быстрого доступа к информации.',
        ),
        category(
            name='Блоки питания',
            description='Устройства, преобразующие электрический ток в пригодную для использования энергию для внутренних компонентов',
        ),
        category(
            name='Корпуса',
            description='Конструктивные элементы, предназначенные для размещения и защиты внутренних компонентов компьютера.',
        ),
        category(
            name='Охлаждение компьютера',
            description='Системы охлаждения для поддержания оптимальной температуры компонентов.',
        ),
        category(
            name='Твердотельные накопители SSD',
            description='Высокоскоростные накопители на основе флэш-памяти, используемые для хранения данных.',
        ),
        category(
            name='Жесткие диски HDD',
            description='Механические накопители на магнитных дисках, обеспечивающие большую ёмкость хранения данных.',
        ),
        category(
            name='Мониторы',
            description='Устройства отображения, используемые для визуализации графической информации от компьютера.',
        ),
    ])

def reverse_populate_categories(apps, schema_editor):
    category = apps.get_model('online_store', 'Category')
    category.objects.filter(
        name__in=[
            'Процессоры',
            'Материнская плата',
            'Видеокарты',
            'Оперативная память',
            'Блоки питания',
            'Корпуса',
            'Охлаждение компьютера',
            'Твердотельные накопители SSD',
            'Жесткие диски HDD',
            'Мониторы',
        ]
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0001_create_categories_table'),
    ]

    operations = [
        migrations.RunPython(populate_categories, reverse_populate_categories),
    ]
