# Generated by Django 6.0.1 on 2026-01-12 16:25

import django.db.models.deletion
from django.db import migrations, models




def get_default_category_id(apps, schema_editor):
    """Поиск или создание в случае отсутствия дефолтной категории"""
    category = apps.get_model('online_store', 'Category')
    try:
        default_category = category.objects.get(name='Без категории')
        return default_category.id
    except category.DoesNotExist:
        default_category = category.objects.create(
            name='Без категории',
            description='Товары без присвоенной категории.'
        )
        return default_category.id

class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0002_init_default_data_for_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('category', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='products',
                    to='online_store.category',
                    default=get_default_category_id
                )),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
